name: shopping_manager
description: A Flutter application for managing shopping lists.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  uuid: ^4.5.1
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

